/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as CriarPersonagemRouteImport } from './routes/criar-personagem'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AguardandoConfirmacaoRouteImport } from './routes/aguardando-confirmacao'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPagamentoRouteImport } from './routes/_authenticated/pagamento'
import { Route as AuthenticatedJogadoresRouteImport } from './routes/_authenticated/jogadores'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicWebhooksSyncpayRouteImport } from './routes/api/public/webhooks/syncpay'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarPersonagemRoute = CriarPersonagemRouteImport.update({
  id: '/criar-personagem',
  path: '/criar-personagem',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AguardandoConfirmacaoRoute = AguardandoConfirmacaoRouteImport.update({
  id: '/aguardando-confirmacao',
  path: '/aguardando-confirmacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPagamentoRoute = AuthenticatedPagamentoRouteImport.update({
  id: '/pagamento',
  path: '/pagamento',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJogadoresRoute = AuthenticatedJogadoresRouteImport.update({
  id: '/jogadores',
  path: '/jogadores',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksSyncpayRoute =
  ApiPublicWebhooksSyncpayRouteImport.update({
    id: '/api/public/webhooks/syncpay',
    path: '/api/public/webhooks/syncpay',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aguardando-confirmacao': typeof AguardandoConfirmacaoRoute
  '/auth': typeof AuthRoute
  '/criar-personagem': typeof CriarPersonagemRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/jogadores': typeof AuthenticatedJogadoresRoute
  '/pagamento': typeof AuthenticatedPagamentoRoute
  '/api/public/webhooks/syncpay': typeof ApiPublicWebhooksSyncpayRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aguardando-confirmacao': typeof AguardandoConfirmacaoRoute
  '/auth': typeof AuthRoute
  '/criar-personagem': typeof CriarPersonagemRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/jogadores': typeof AuthenticatedJogadoresRoute
  '/pagamento': typeof AuthenticatedPagamentoRoute
  '/api/public/webhooks/syncpay': typeof ApiPublicWebhooksSyncpayRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/aguardando-confirmacao': typeof AguardandoConfirmacaoRoute
  '/auth': typeof AuthRoute
  '/criar-personagem': typeof CriarPersonagemRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/jogadores': typeof AuthenticatedJogadoresRoute
  '/_authenticated/pagamento': typeof AuthenticatedPagamentoRoute
  '/api/public/webhooks/syncpay': typeof ApiPublicWebhooksSyncpayRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aguardando-confirmacao'
    | '/auth'
    | '/criar-personagem'
    | '/sitemap.xml'
    | '/jogadores'
    | '/pagamento'
    | '/api/public/webhooks/syncpay'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aguardando-confirmacao'
    | '/auth'
    | '/criar-personagem'
    | '/sitemap.xml'
    | '/jogadores'
    | '/pagamento'
    | '/api/public/webhooks/syncpay'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/aguardando-confirmacao'
    | '/auth'
    | '/criar-personagem'
    | '/sitemap.xml'
    | '/_authenticated/jogadores'
    | '/_authenticated/pagamento'
    | '/api/public/webhooks/syncpay'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AguardandoConfirmacaoRoute: typeof AguardandoConfirmacaoRoute
  AuthRoute: typeof AuthRoute
  CriarPersonagemRoute: typeof CriarPersonagemRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicWebhooksSyncpayRoute: typeof ApiPublicWebhooksSyncpayRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar-personagem': {
      id: '/criar-personagem'
      path: '/criar-personagem'
      fullPath: '/criar-personagem'
      preLoaderRoute: typeof CriarPersonagemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aguardando-confirmacao': {
      id: '/aguardando-confirmacao'
      path: '/aguardando-confirmacao'
      fullPath: '/aguardando-confirmacao'
      preLoaderRoute: typeof AguardandoConfirmacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/pagamento': {
      id: '/_authenticated/pagamento'
      path: '/pagamento'
      fullPath: '/pagamento'
      preLoaderRoute: typeof AuthenticatedPagamentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jogadores': {
      id: '/_authenticated/jogadores'
      path: '/jogadores'
      fullPath: '/jogadores'
      preLoaderRoute: typeof AuthenticatedJogadoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/syncpay': {
      id: '/api/public/webhooks/syncpay'
      path: '/api/public/webhooks/syncpay'
      fullPath: '/api/public/webhooks/syncpay'
      preLoaderRoute: typeof ApiPublicWebhooksSyncpayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedJogadoresRoute: typeof AuthenticatedJogadoresRoute
  AuthenticatedPagamentoRoute: typeof AuthenticatedPagamentoRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedJogadoresRoute: AuthenticatedJogadoresRoute,
  AuthenticatedPagamentoRoute: AuthenticatedPagamentoRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AguardandoConfirmacaoRoute: AguardandoConfirmacaoRoute,
  AuthRoute: AuthRoute,
  CriarPersonagemRoute: CriarPersonagemRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicWebhooksSyncpayRoute: ApiPublicWebhooksSyncpayRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
